### ISSUE TITLE
Installing/building wheel on PyPy does not work (cffi/C extension related)

### ISSUE THREAD

**Issue by HGStyle** [indygreg/python-zstandard#260]
Output log + command:

```
$ pypy3 --version
Python 3.10.14 (7.3.17+dfsg-2~ppa1~ubuntu22.04, Sep 08 2024, 10:09:55)
[PyPy 7.3.17 with GCC 11.4.0]
$ pypy3 -m pip install zstandard==0.23.0 --break-system-packages
Defaulting to user installation because normal site-packages is not writeable
Collecting zstandard==0.23.0
  Using cached zstandard-0.23.0.tar.gz (681 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cffi>=1.11 in /usr/lib/pypy3.10 (from zstandard==0.23.0) (1.17.0)
Collecting pycparser (from cffi>=1.11->zstandard==0.23.0)
  Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Building wheels for collected packages: zstandard
  Building wheel for zstandard (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for zstandard (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      <string>:41: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      <string>:42: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      not modified: 'build/zstandard/_cffi.c'
      generating build/zstandard/_cffi.c
      (already up-to-date)
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-pypy310
      creating build/lib.linux-x86_64-pypy310/zstandard
      copying zstandard/__init__.py -> build/lib.linux-x86_64-pypy310/zstandard
      copying zstandard/backend_cffi.py -> build/lib.linux-x86_64-pypy310/zstandard
      copying zstandard/__init__.pyi -> build/lib.linux-x86_64-pypy310/zstandard
      copying zstandard/py.typed -> build/lib.linux-x86_64-pypy310/zstandard
      running build_ext
      building 'zstandard._cffi' extension
      creating build/temp.linux-x86_64-pypy310
      creating build/temp.linux-x86_64-pypy310/build
      creating build/temp.linux-x86_64-pypy310/build/zstandard
      creating build/temp.linux-x86_64-pypy310/zstd
      gcc -pthread -DNDEBUG -O2 -fPIC -I/tmp/pip-install-5vxjl8dg/zstandard_c77efa6a496e4a81928b5eb618f52ac8/zstd -I/usr/include/pypy3.10 -c build/zstandard/_cffi.c -o build/temp.linux-x86_64-pypy310/build/zstandard/_cffi.o
      build/zstandard/_cffi.c:50:14: fatal error: pyconfig.h: Aucun fichier ou dossier de ce nom
         50 | #    include <pyconfig.h>
            |              ^~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for zstandard
Failed to build zstandard
ERROR: Failed to build installable wheels for some pyproject.toml based projects (zstandard)
```

Also tried other versions: 0.22.0; 0.14.1 (other people reported this working on PyPy, but it doesn't for me); 0.15.0; 0.15.1; 0.15.2

**Comment by indygreg** [comment]
The error is for a missing `pyconfig.h` file. That implies your machine / build environment doesn't have the Python development dependencies installed or findable.

The `main` branch CI does build fine with PyPy. So I think the issue is just on your machine.

**Comment by HGStyle** [comment]
Oh yeah, I have no idea what I was trying to do, but I got it installed now. But I still don't remember what did I needed it for. Thanks
